<h3 style="color:blue" align="left">Numpy</h3>

In [2]:
import numpy as np

#### Array attributes

In [10]:
a = np.array([1, 2, 3])                            # Create a rank 1 array

print("a-type: ",type(a))                          # Prints "<class 'numpy.ndarray'>"
print("a-shape:",a.shape)                          # Prints (rows, columns)
print("a-index:",a[0], a[1], a[2])                 # Prints "1 2 3" = indexing
a[0] = 5                                           # Change an element of the array
print("a-changed list:", a)                        # Prints "[5, 2, 3]"
print("a-dimensions:",a.ndim)

b = np.array([[1,2,3],[4,5,6]])                    # Create a rank 2 array
print("b-shape:",b.shape)                          # Prints "(2, 3)"

c=b.reshape(3,2)
print("b-reshape:",c)
print("b-index:",b[0, 0], b[0, 1], b[1, 0])        # Prints "1 2 4"
print("array-dimensions:",b.ndim)

d=b.ravel()
print("b-ravel:",d)
print("b:",b)                                      # original array remains

print(b.flatten())

a-type:  <class 'numpy.ndarray'>
a-shape: (3,)
a-index: 1 2 3
a-changed list: [5 2 3]
a-dimensions: 1
b-shape: (2, 3)
b-reshape: [[1 2]
 [3 4]
 [5 6]]
b-index: 1 2 4
array-dimensions: 2
b-ravel: [1 2 3 4 5 6]
b: [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


#### Create arrays

In [38]:
a = np.zeros((2,4))                                # Create an array of all zeros, floating type hence decimal
print("zeros:",a)

b = np.ones((3,2))                                 # Create an array of all ones
print("ones:",b)

f = np.empty((3,3))                                # Create an array of random values
print("empty:",f)              

c = np.full((2,2), 7)                              # Create a constant array
print("full:",c)

d = np.eye(5,4)                      # Create a 2x2 identity matrix; an identity matrix is a square matrix with ones on the diagonal and zeros elsewhere
print("eye:",d)

e = np.random.random((2,2))                        # Create an array filled with random values
print("random:",e)

# Converting from a list
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)
print("list",my_list1,"to array",my_array1)

#create list
g=np.arange(2,4,0.2)                               # arange(start,stop,step)
print("arange:",g)

# linear spaced array
h=np.linspace(1,5,10)
print("linear space:",h)

zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones: [[1. 1.]
 [1. 1.]
 [1. 1.]]
empty: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
full: [[7 7]
 [7 7]]
eye: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
random: [[0.38563308 0.32701903]
 [0.58979771 0.85645906]]
list [1, 2, 3, 4] to array [1 2 3 4]
arange: [2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8]
linear space: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


#### Multi Dimensional Array

In [27]:
my_list2 = [11,22,33,44]
my_lists = [my_list1,my_list2]
my_array2 = np.array(my_lists)
my_array2

print(my_array2)
print(my_array2.shape)
print(my_array2.dtype)

[[ 1  2  3  4]
 [11 22 33 44]]
(2, 4)
int32


#### Numpy List vs Python List
Numpy takes less memory and is faster, has built in math function

In [2]:
import numpy as np
import time
import sys
SIZE = 1000000                                                     # 1m elements
l1 = range(SIZE)
l2 = range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)               # faster
print("python list memory:",sys.getsizeof(l1)*len(l1))             # less momery
# numpy array     
start= time.time()
result = a1 + a2                                                   # use of built-in function
print("numpy took: ", (time.time()-start)*1000)
print("numpy list memory:",a1.nbytes)

python list took:  104.28190231323242
python list memory: 48000000
numpy took:  17.58551597595215
numpy list memory: 4000000


#### Methods

In [9]:
a=np.array([[1,5,3,2],[4,7,6,5]])
print("Dimension:",a.ndim)
print("Item Size Integer:",a.itemsize)                        # integer has 4byte size
a=np.array([[1,5,3,2],[4,7,6,5]],dtype=np.float64)
print("Item Size Float:",a.itemsize)                          # float has 8byte size
       
print("Number of elements:",a.size)                           # number of elements
print("Shape of array:",a.shape)                              # number of rows, columns

np.sort(a)

Dimension: 2
Item Size Integer: 4
Item Size Float: 8
Number of elements: 8
Shape of array: (2, 4)


array([[1., 2., 3., 5.],
       [4., 5., 6., 7.]])

#### Scalars

In [49]:
a=np.arange(3,30,3).reshape(3,3)
print('reshape-a',a)

b=np.arange(2,20,2).reshape(3,3)
print('reshape-b',b)

## multiply
print('Multiply a*a:',a*a)
print('Multiply a*b:',a*b)

## Subtract
print('Subtract a-b',a-b)

## division
print('Divide 1/a',1/a)
print('Divide a/b',a/b)

## Exponential
print('Exponential a**3',a**3)

## Sum
print("a =",a)
print("sum of axis 0 in a =",a.sum(axis=0))                # Axis 0 is column, axis 1 is row

## Min & Max
print("max in a:",a.max())
print("min in a:",a.min())

reshape-a [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
reshape-b [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Multiply a*a: [[  9  36  81]
 [144 225 324]
 [441 576 729]]
Multiply a*b: [[  6  24  54]
 [ 96 150 216]
 [294 384 486]]
Subtract a-b [[1 2 3]
 [4 5 6]
 [7 8 9]]
Divide 1/a [[0.33333333 0.16666667 0.11111111]
 [0.08333333 0.06666667 0.05555556]
 [0.04761905 0.04166667 0.03703704]]
Divide a/b [[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
Exponential a**3 [[   27   216   729]
 [ 1728  3375  5832]
 [ 9261 13824 19683]]
a = [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
sum of axis 0 in a = [36 45 54]
max in a: 27
min in a: 3


#### Indexing & Slicing

In [51]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]
print("1",b)
print("2",a[0, 3])
b[0, 0] = 77                                           # b[0, 0] is the same piece of data as a[0, 1]
print("3",b)
print("4",a[0, 1])

row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

print(a)

c=a.copy()
print(c)

1 [[2 3]
 [6 7]]
2 4
3 [[77  3]
 [ 6  7]]
4 77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Reshape

In [98]:
a=np.arange(0,6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
c=np.arange(12,18).reshape(3,2)

print('a',a)
print('b',b)

print('c',c)

print('vstack',np.vstack((a,b,c)))

d=np.hstack((a,b,c))
print('d',d)

e=np.hsplit(d,2)
print('e',e)

f=np.vsplit(d,3)
print('f',f)

a [[0 1]
 [2 3]
 [4 5]]
b [[ 6  7]
 [ 8  9]
 [10 11]]
c [[12 13]
 [14 15]
 [16 17]]
vstack [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
d [[ 0  1  6  7 12 13]
 [ 2  3  8  9 14 15]
 [ 4  5 10 11 16 17]]
e [array([[ 0,  1,  6],
       [ 2,  3,  8],
       [ 4,  5, 10]]), array([[ 7, 12, 13],
       [ 9, 14, 15],
       [11, 16, 17]])]
f [array([[ 0,  1,  6,  7, 12, 13]]), array([[ 2,  3,  8,  9, 14, 15]]), array([[ 4,  5, 10, 11, 16, 17]])]


#### Indexing with Boolean Arrays

In [3]:
a=np.arange(12).reshape(3,4)
print(a)

b=a>5
print(b,b.dtype)

print(a[b])

a[b]=-100
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]] bool
[ 6  7  8  9 10 11]
[[   0    1    2    3]
 [   4    5 -100 -100]
 [-100 -100 -100 -100]]


#### Iterate thru array

In [13]:
a = np.arange(12).reshape(3,4)
print(a)
for row in a:
    for cell in row:
        print("cell:",cell)

for x in np.nditer(a, order='C'):                        # READ ROW BY ROW
    print("nditer-C:",x)

for x in np.nditer(a, order='F'):                        # READ column BY column
    print("nditer-F:",x)

for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

b = np.arange(3, 15, 4).reshape(3,1)
for x, y in np.nditer([a,b]):
    print ('x,y',x,y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
cell: 0
cell: 1
cell: 2
cell: 3
cell: 4
cell: 5
cell: 6
cell: 7
cell: 8
cell: 9
cell: 10
cell: 11
nditer-C: 0
nditer-C: 1
nditer-C: 2
nditer-C: 3
nditer-C: 4
nditer-C: 5
nditer-C: 6
nditer-C: 7
nditer-C: 8
nditer-C: 9
nditer-C: 10
nditer-C: 11
nditer-F: 0
nditer-F: 4
nditer-F: 8
nditer-F: 1
nditer-F: 5
nditer-F: 9
nditer-F: 2
nditer-F: 6
nditer-F: 10
nditer-F: 3
nditer-F: 7
nditer-F: 11
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
x,y 0 3
x,y 1 3
x,y 2 3
x,y 3 3
x,y 4 7
x,y 5 7
x,y 6 7
x,y 7 7
x,y 8 11
x,y 9 11
x,y 10 11
x,y 11 11


#### Integer Array Indexing

In [89]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


#### Array Transpose

In [12]:
a = np.arange(20).reshape(4,5)
print(a)
print(a.shape)

b=a.T
print(b)
print(b.shape)

np.dot(a,b)
#=+A1*$A$7+B1*$A$8+C1*$A$9+D1*$A$10+E1*$A$11	=+A1*$B$7+B1*$B$8+C1*$B$9+D1*$B$10+E1*$B$11	=+A1*$C$7+B1*$C$8+C1*$C$9+D1*$C$10+E1*$C$11	=+A1*$D$7+B1*$D$8+C1*$D$9+D1*$D$10+E1*$D$11
#=+A2*$A$7+B2*$A$8+C2*$A$9+D2*$A$10+E2*$A$11	=+A2*$B$7+B2*$B$8+C2*$B$9+D2*$B$10+E2*$B$11	=+A2*$C$7+B2*$C$8+C2*$C$9+D2*$C$10+E2*$C$11	=+A2*$D$7+B2*$D$8+C2*$D$9+D2*$D$10+E2*$D$11
#=+A3*$A$7+B3*$A$8+C3*$A$9+D3*$A$10+E3*$A$11	=+A3*$B$7+B3*$B$8+C3*$B$9+D3*$B$10+E3*$B$11	=+A3*$C$7+B3*$C$8+C3*$C$9+D3*$C$10+E3*$C$11	=+A3*$D$7+B3*$D$8+C3*$D$9+D3*$D$10+E3*$D$11
#=+A4*$A$7+B4*$A$8+C4*$A$9+D4*$A$10+E4*$A$11	=+A4*$B$7+B4*$B$8+C4*$B$9+D4*$B$10+E4*$B$11	=+A4*$C$7+B4*$C$8+C4*$C$9+D4*$C$10+E4*$C$11	=+A4*$D$7+B4*$D$8+C4*$D$9+D4*$D$10+E4*$D$11


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
(5, 4)


array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

#### 3D array

In [14]:
a=np.arange(20).reshape(5,2,2)
print(a)

print(a.T)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
[[[ 0  4  8 12 16]
  [ 2  6 10 14 18]]

 [[ 1  5  9 13 17]
  [ 3  7 11 15 19]]]


#### Swap Axis

In [20]:
#a=np.array([[1,2,3]])
print(a)
print(a.swapaxes(0,1))
print(a.swapaxes(1,2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
[[[ 0  1]
  [ 4  5]
  [ 8  9]
  [12 13]
  [16 17]]

 [[ 2  3]
  [ 6  7]
  [10 11]
  [14 15]
  [18 19]]]
[[[ 0  2]
  [ 1  3]]

 [[ 4  6]
  [ 5  7]]

 [[ 8 10]
  [ 9 11]]

 [[12 14]
  [13 15]]

 [[16 18]
  [17 19]]]


#### Array Functions

In [41]:
a=np.arange(10)

b=np.sqrt(a)
c=np.exp(a)
d=np.std(a)
print(b)
print(c)
print(d)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
2.8722813232690143


In [14]:
print(np.add(b,c))
print(np.maximum(b,c))

[[ 4  5]
 [10 11]
 [16 17]]
[[ 3  3]
 [ 7  7]
 [11 11]]


#### Save as npy file

In [47]:
a=np.arange(5)
print('a',a)
b=np.arange(7)
print('b',b)
np.save('myarray',a)
arr1=np.load('myarray.npy')
print("saved array",arr1)

np.savez('myarray1.npz',x=a,y=b)           # save as zip file
arr2=np.load('myarray1.npz')
print('zipped array',arr2['x'])

np.savetxt('myarraytxt.txt',b,delimiter=",")
arr3=np.loadtxt('myarraytxt.txt',delimiter=',')
print('txt file',arr3)

a [0 1 2 3 4]
b [0 1 2 3 4 5 6]
saved array [0 1 2 3 4]
zipped array [0 1 2 3 4]
txt file [0. 1. 2. 3. 4. 5. 6.]
