#### Numpy - copies and views

In [3]:
import numpy as np

my_vector = np.array([1, 2, 3, 4])
my_vector

array([1, 2, 3, 4])

In [4]:
my_subset = my_vector[1:3]
my_subset

array([2, 3])

In [5]:
my_subset[0] = -99

In [6]:
my_subset

array([-99,   3])

In [7]:
my_vector

array([  1, -99,   3,   4])

#### pandas - copies and views

In [20]:
df1 = pd.DataFrame({"a": [10, 20, 30, 40], "b": [11, 12, 13, 14]})
print(df1)

    a   b
0  10  11
1  20  12
2  30  13
3  40  14


In [21]:
slice = df.iloc[1:3,]                
print(slice)

    a   b
1  20  -1
2  30  13


In [23]:
df.iloc[1, 1] = -1          
print(df)

    a   b
0  10  11
1  20  -1
2  30  13
3  40  14


In [24]:
print(slice)

    a   b
1  20  -1
2  30  13


#### Copy-on-Write (CoW)

#### The idea of Copy-on-Write is that, from the perspective of the user, pandas behaves as if all operations return a copy.
####  pandas will create a view (so it's faster) and make a note that if either the original array or the subset are ever changed, it needs to actually make the copy before allowing those changes to take place

In [12]:
import pandas as pd
pd.set_option("mode.copy_on_write", True)

In [14]:
df = pd.DataFrame({"a": [10, 20, 30, 40], "b": [11, 12, 13, 14]})
print(df)

    a   b
0  10  11
1  20  12
2  30  13
3  40  14


In [16]:
slice = df.iloc[1:3,]                  # created as view not as a copy
print(slice)

    a   b
1  20  12
2  30  13


In [22]:
df.iloc[1, 1] = -1                     # in background, slice converted to copy
print(df)

    a   b
0  10  11
1  20  -1
2  30  13
3  40  14


In [19]:
print(slice)

    a   b
1  20  12
2  30  13
