In [1]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)
my_slice = my_array[1:3]
my_slice

[1 2 3 4 5]


array([2, 3])

In [2]:
my_array = np.array([1, 2, 3, 4, 5])
my_slice = my_array[1:3]
my_array = my_array * 2
my_slice

array([2, 3])

In [3]:
my_array = np.array([1, 2, 3, 4, 5])
my_slice = my_array[1:3]
my_array[:] = my_array * 2
my_slice

array([4, 6])

In [4]:
my_array = np.array([1, 2, 3, 4, 5])
my_slice = my_array[1:3].copy()
my_array[:] = my_array * 2
my_slice

array([2, 3])

In [5]:
my_array = np.array([1, 2, 3, 4, 5])
my_slice = my_array[[1, 2]]
my_array[:] = my_array * 2
my_slice

array([2, 3])

In [6]:
my_array = np.array([1, 2, 3, 4, 5])
my_slice = my_array[1:3]
my_slice[0] = -99
my_array

array([  1, -99,   3,   4,   5])

In [7]:
my_array = np.array([1, 2, 3, 4, 5])
my_slice = my_array[1:3]
my_array = my_array * 2
my_slice[0] = -99
my_array

array([ 2,  4,  6,  8, 10])

In [8]:
my_slice

array([-99,   3])