In [ ]:
Numpy shapes

In [2]:
import numpy as np

In [20]:
# 1D array, shape is number of elements
survey_1 = np.array(
    [20, 22_000, 12]
)

print(survey_1)
survey_1.shape

[   20 22000    12]


(3,)

In [23]:
# 2D array, shape is (row,column)
survey_2 = np.array(
    [[20, 22_000, 12], [35, 65_000, 16]]
)

print(survey_2)
survey_2.shape

[[   20 22000    12]
 [   35 65000    16]]


(2, 3)

In [27]:
# 2D array, shape is (dimension,row,column)

survey_2a = np.array(
    [[[20, 22_000, 12], [35, 65_000, 16]], [[55, 19_000, 11], [45, 35_000, 12]]]
)

print(survey_2a)
survey_2a.shape

[[[   20 22000    12]
  [   35 65000    16]]

 [[   55 19000    11]
  [   45 35000    12]]]


(2, 2, 3)

In [28]:
# 3D array, shape is (dimension,row,column)

survey_3 = np.array(
    [[[20, 22_000, 12], [35, 65_000, 16]], [[55, 19_000, 11], [45, 35_000, 12]], [[55, 19_000, 11], [45, 35_000, 12]]]
)

print(survey_3)
survey_3.shape

[[[   20 22000    12]
  [   35 65000    16]]

 [[   55 19000    11]
  [   45 35000    12]]

 [[   55 19000    11]
  [   45 35000    12]]]


(3, 2, 3)

#### Slicing array

In [17]:
a=np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [4]:
b=a[:2,1:]
print(b)
b.shape

[[2 3]
 [5 6]]


(2, 2)

In [5]:
c=a[2]
print(c)
c.shape

[7 8 9]


(3,)

In [6]:
d=a[2,:]
print(d)
d.shape

[7 8 9]


(3,)

In [7]:
e=a[2:,:]
print(e)
e.shape

[[7 8 9]]


(1, 3)

In [8]:
f=a[:,:2]
print(f)
f.shape

[[1 2]
 [4 5]
 [7 8]]


(3, 2)

In [9]:
g=a[1,:2]
print(g)
g.shape

[4 5]


(2,)

In [10]:
h=a[1:2,:2]
print(h)
h.shape

[[4 5]]


(1, 2)